app/share/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.ShareCreateView.as_view(), name="create-share"),
    path("delete/<int:pk>", views.DeleteShareView.as_view(), name="delete-share"),
    path("<uuid:pk>", views.DetailShareView.as_view(), name="detail-share"),
    path(
        "comment/<uuid:pk>/<int:ticket_pk>",
        views.ShareCommentCreateView.as_view(),
        name="comment-share",
    ),
]

app/ticsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("users.urls")),
    path("reports/", include("reports.urls")),
    path("share/", include("share.urls")),
    path("manufactures/", include("manufactures.urls")),
    path("storage/", include("storage.urls")),
    path("", include("ticket.urls")),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    if settings.USE_DEBUG_TOOLBAR:
        from debug_toolbar.toolbar import debug_toolbar_urls

        urlpatterns += debug_toolbar_urls()

app/share/models.py
import uuid

from django.conf import settings
from django.contrib.sites.models import Site
from django.db import models


class Share(models.Model):
    class Meta:
        verbose_name = "Ссылка на заявку"
        verbose_name_plural = "Ссылки на заявки"
        ordering = ["-created_at"]

    uuid = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    ticket = models.OneToOneField(
        "ticket.Ticket", on_delete=models.CASCADE, related_name="share"
    )
    creator = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="shares"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    # TODO: rename share to resolve func
    def get_absolute_url(self):
        return f"{settings.PROTOCOL}://{Site.objects.get_current()}/share/{self.uuid}"

app/share/forms.py
from django import forms

from ticsys.fields import MultipleFileField

from .models import Share
from ticket.models import Comment


class ShareForm(forms.ModelForm):
    class Meta:
        model = Share
        fields = [
            "ticket",
        ]


class CommentShareForm(forms.ModelForm):
    files = MultipleFileField(
        required=False,
        help_text="Файлы",
        label="Прикрепить файлы",
    )

    user_fingerprint = forms.CharField(
        required=False, widget=forms.HiddenInput(), label="user_fingerprint"
    )

    class Meta:
        model = Comment
        fields = [
            "text",
        ]

        widgets = {
            "is_for_report": forms.HiddenInput(),
        }

app/share/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext as _
from django.http import Http404, JsonResponse
from django.views.generic import CreateView, DeleteView, DetailView
from django.urls import reverse_lazy, reverse
from ticket.utils import is_image

from ticket.models import Comment, CommentImage, CommentFile
from ticket.mixin import AccessOperatorMixin
from users.models import User
from .models import Share
from .forms import ShareForm, CommentShareForm

from ticket.models import Ticket


class BaseShareView:
    def check_access(self, ticket: Ticket):
        if not self.request:
            return False
        if self.request.user.is_staff:
            return True

        if ticket.customer.profile.linked_operators.filter(
            pk=self.request.user.pk
        ).exists():
            return True
        return False


class ShareCreateView(
    LoginRequiredMixin, AccessOperatorMixin, CreateView, BaseShareView
):
    model = Share
    form_class = ShareForm
    success_url = reverse_lazy("create-share")

    def form_valid(self, form):
        if not self.check_access(form.cleaned_data.get("ticket")):
            return JsonResponse({"error": "Access denied"}, status=403)
        share: Share = form.save(commit=False)
        share.creator = self.request.user
        share.save()

        return JsonResponse({"uuid": share.uuid, "link": share.get_absolute_url()})


class DeleteShareView(
    LoginRequiredMixin, AccessOperatorMixin, DeleteView, BaseShareView
):
    model = Share
    success_url = reverse_lazy("create-share")
    queryset = Ticket.objects.all()

    def get_object(self):
        ticket = super().get_object()
        if ticket.share:
            obj = ticket.share
            return obj
        raise Http404(
            _("No %(verbose_name)s found matching the query")
            % {"verbose_name": queryset.model._meta.verbose_name}
        )

    def form_valid(self, form):
        if not self.check_access(self.object.ticket):
            return JsonResponse({"error": "Access denied"}, status=403)
        super().form_valid(form)
        return JsonResponse({"status": 200})

    def form_invalid(self, form):
        return JsonResponse({"status": "error"}, status_code=400)


class DetailShareView(DetailView):
    model = Ticket
    template_name = "share/detail.html"

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)

        if self.object.phone:
            kwargs["phones"] = self.object.phone.splitlines()

        return kwargs

    def get_object(self, *args, **kwargs):
        ticket = get_object_or_404(Ticket, share=self.kwargs["pk"])
        return ticket


class ShareCommentCreateView(CreateView):
    model = Comment
    form_class = CommentShareForm
    template_name = "share/comment_modal_form.html"

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs.update({"share": Share.objects.get(pk=self.kwargs.get("pk"))})
        return kwargs

    def get_success_url(self) -> str:
        return reverse("detail-share", kwargs={"pk": self.kwargs.get("pk")})

    def form_valid(self, form):
        ticket: Ticket = Ticket.objects.get(pk=self.kwargs.get("ticket_pk"))
        self.object: Comment = form.save(commit=False)
        files = self.request.FILES.getlist("files")

        self.object.ticket = ticket
        self.object.author = self.get_or_create_user(
            form.cleaned_data.get("user_fingerprint")
        )
        self.object: Comment = form.save()
        for file in files:
            if is_image(file):
                CommentImage.objects.create(image=file, comment=self.object)
                continue
            CommentFile.objects.create(file=file, comment=self.object)
        return super().form_valid(form)

    def get_or_create_user(self, fingerprint):
        if self.request.user and not self.request.user.is_anonymous:
            return self.request.user
        if not fingerprint:
            user = User.objects.create(
                username="without_fingerprint",
                is_active=False,
                first_name="Неопознанный",
                last_name="Пользователь",
            )
            user.last_name = "Пользователь %s" % user.pk
            user.save(update_fields=["last_name"])
            return user
        user, created = User.objects.get_or_create(
            username=fingerprint,
            defaults={
                "is_active": False,
                "first_name": "Неопознанный",
                "last_name": "Пользователь",
                "role": User.Role.OTHER,
            },
        )
        if created:
            user.last_name = "Пользователь %s" % user.pk
            user.save(update_fields=["last_name"])
        return user

app/share/templates/share/comment_modal_form.html
<div class="ui modal" id="CommentShareFormModal">
    <i class="close icon"></i>
    <div class="header">Добавить комментарий</div>
    <div class="content">
      <form class="ui form" method="post" enctype="multipart/form-data" action={% url 'comment-share' share.uuid  share.ticket.pk %} >
          {{ form.non_field_errors }}
          {% csrf_token %}
          {% for field in form %}
          <div class="field">
              {{ field.errors }}
              {% if not field.is_hidden%}
              {{ field.label_tag }} 
              {% endif %}
              {{ field }}
          </div>
          {% endfor %}
          <button class="ui button positive" type="submit">Изменить</button>
  
      </form>
    </div>

</div>

app/share/templates/share/detail.html
{% extends 'ticsys/base.html' %}
{% load static %}
{% block header_style %}
<link rel="stylesheet" type="text/css" href="{% static 'DataTables/DataTables-1.13.1/css/dataTables.semanticui.min.css' %}"/> 
<script type="text/javascript" src="{% static 'DataTables/DataTables-1.13.1/js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'DataTables/DataTables-1.13.1/js/dataTables.semanticui.min.js' %}"></script>
<style>
body:{
  background: -webkit-linear-gradient(to right, #E2E2E2, #C9D6FF);
  background: linear-gradient(to right, #E2E2E2, #C9D6FF);
}
</style>
{% endblock %}
{% block common_content %}
<div class="ui container segment">
  {% if request.user.is_anonymous %}
  <h1>Заявка №{{ticket.pk}}</h1>
  {% else %}
  <a href={% url 'ticket-update' ticket.pk %}> <h1> Заявка №{{ticket.pk}}</h1> </a>
  {% endif %}
  <div class="ui grid container">
    <div class="four wide column">
      <div class="ui list">
        {% if ticket.phone %}
        <div class="item">
          <i class="phone icon"></i>
          <div class="content">
            {% for phone  in phones %}
              <a href="tel:{{phone}}"> {{phone}}</a>
            {% endfor %}
          </div>
        </div>
        {%endif%}
        {% if ticket.address%}
        <div class="item">
          <i class="marker icon"></i>
          <div class="content">
            {{ticket.address}}
          </div>
        </div>
        {%endif%}
        {% if ticket.shop_id%}
        <div class="item">
          <i class="store alternate icon"></i>
          <div class="content">
            {{ticket.shop_id}}
          </div>
        </div>
        {%endif%}
        {% if ticket.full_name%}
        <div class="item">
          <i class="user icon"></i>
          <div class="content">
            {{ticket.full_name}}
          </div>
        </div>
        {%endif%}
        {% if ticket.position%}
        <div class="item">
          <i class="id badge icon"></i>
          <div class="content">
            {{ticket.position}}
          </div>
        </div>
        {%endif%}
        {% if ticket.sap_id%}
        <div class="item">
          <i class="ticket icon"></i>
          <div class="content">
            SAP: {{ticket.sap_id}}
          </div>
        </div>
        {%endif%}
        {% if ticket.metadata%}
        <div class="item">
          <i class="info icon"></i>
          <div class="content">
            {{ticket.metadata}}
          </div>
        </div>
        {%endif%}
        {% if ticket.act.file_doc_act %}
          <div class="item">
            <i class="file alternate icon"></i>
            <div class="content">
              <a href="{{ticket.act.file_doc_act.url}}" target="_blank">Скачать акт</a>
            </div>
          </div>
        {% else %}
          <div class="item">
            <i class="file alternate icon"></i>
            <div class="content">
              <a href="{% url 'act-create' ticket.pk %}">Создать акт</a>
            </div>
          </div>
          
        {% endif %}
        

      </div>
    </div>
    <div class="twelve wide column">
      <div class="ui   ">
        <div class="ui horizontal list">    
          <div class="item"> 
            <div class="header"> Тип</div> 
            {% firstof ticket.type_ticket "<i>Не назначен</i>"%}

          </div>
          <div class="item"> 
            <div class="header"> Заказчик</div> 
            {{ticket.customer.get_role_user}}
          </div>
          <div class="item"> 
            <div class="header"> Исполнитель</div> 
            {% if ticket.contractor %}
            {{ticket.contractor}}
            {% if ticket.contractor.phone %}
            <a href="tel:{{ticket.contractor.phone}}">{{ticket.contractor.phone}}</a>
            {% endif %}
            {% else %}
            <i>Не назначен</i>
            {% endif %}
          </div>
          <div class="item"> 
            <div class="header"> Статус</div> 
            {% if ticket.status %} <div class="ui {{ticket.get_color_status}} label">{{ticket.status}}</div>{% endif %}
          </div>
          <div class="item"> 
            <div class="header"> Плановая дата выезда/исполнения</div> 
            {% if ticket.planned_execution_date %}
            {{ticket.planned_execution_date}}
            {% else%}
            <i>Не назначена</i>
            {% endif %}
          </div>
        </div>
        <div class=" ui list ">
          <div class="item"> 
            <div class="header"> Описание</div> 
            <div class="ui large text">
            {{ticket.description|safe|linebreaksbr|urlize }}
            </div>
          </div>
        </div>
        <div class="ui grid container">

          <div class="two wide column">
            <button class="ui right floated info button" id="showCommentModalBtn"> Добавить комментарий</button>
          </div>

      </div>
    </div>
    
  <div class="ui comments">
  {% for comment in ticket.comments.all %}
    {% include "ticket/ticket_comment_list.html" %}
  {% endfor %}
  </div>
</div>
{% endblock common_content %}
{% block script %}
<script>
  var visitorId = ""
    const fpPromise = import("{% static 'share/js/v3.js' %}")
      .then(FingerprintJS => FingerprintJS.load())
  
    fpPromise
      .then(fp => fp.get())
      .then(result => {
        visitorId = result.visitorId
      })
      .catch(error => console.error(error))

  $('.circle.icon').popup();
  

  fetch('{% url "comment-share" ticket.share.uuid ticket.pk %}')
    .then(res => res.text())
    .then(result => {
      let div = document.createElement('div');
      $(div).html(result);
      document.body.append(div);
      $("#CommentShareFormModal")
      .modal({
        onShow: ()=>{
          $("#id_user_fingerprint").val(visitorId)
        }
      })
      .modal("attach events", "#showCommentModalBtn", "show");
      
    });    



</script>
{% endblock script %}