app/manufactures/urls.py
from django.urls import path
import manufactures.views as views
from rest_framework.routers import DefaultRouter
from .apiviews import ManufactureDataTableAPIView



urlpatterns = [
    path("", views.ManufacturesListView.as_view(), name="manufactures-list"),
    path("create/", views.ManufactureCreateView.as_view(), name="manufactures-create"),
    path("<int:pk>/", views.ManufactureUpdateView.as_view(), name="manufacture-update"),
    path(
        "get_ticket",
        views.ManufactureGetTicket.as_view(),
        name="manufacture-form-get-ticket",
    ),
    path("client/create/", views.ClientCreateView.as_view(), name="client-create"),
    path(
        "nomenclature/create/",
        views.NomenclatureCreateView.as_view(),
        name="nomenclature-create",
    ),
    path(
        "<int:pk>/nomenclatures/",
        views.ManufactureNomenclaturesView.as_view(),
        name="manufacture-detail-nomenclatures",
    ),
    path(
        "status/<int:pk>/",
        views.ManufactureStatusUpdateView.as_view(),
        name="manufacture-update-status",
    ),
    path(
        "nomenclature/<int:pk>/delete/",
        views.DeleteNomenclature.as_view(),
        name="nomenclature-delete",
    ),
    path(
        "<int:pk>/print/",
        views.ManufactureNomenclaturesPrintView.as_view(),
        name="manufacture-detail-nomenclatures-print",
    ),
    path(
        "api/manufactures",
        ManufactureDataTableAPIView.as_view(),
        name="api-manufactures",
    ),
]

app/share/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.ShareCreateView.as_view(), name="create-share"),
    path("delete/<int:pk>", views.DeleteShareView.as_view(), name="delete-share"),
    path("<uuid:pk>", views.DetailShareView.as_view(), name="detail-share"),
    path(
        "comment/<uuid:pk>/<int:ticket_pk>",
        views.ShareCommentCreateView.as_view(),
        name="comment-share",
    ),
]

app/ticsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("users.urls")),
    path("reports/", include("reports.urls")),
    path("share/", include("share.urls")),
    path("manufactures/", include("manufactures.urls")),
    path("storage/", include("storage.urls")),
    path("", include("ticket.urls")),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    if settings.USE_DEBUG_TOOLBAR:
        from debug_toolbar.toolbar import debug_toolbar_urls

        urlpatterns += debug_toolbar_urls()

app/manufactures/models.py
import re

from django.db import models
from django.urls import reverse

from additionally.models import Dictionary
from users.models import Operator
from ticket.models import Ticket

import logging


def get_default_new_manufacture_status():
    status, _ = Dictionary.objects.get_or_create(
        code="new_manufacture_task", type_dict__code="status_manufactory"
    )
    return status


#  Option
class Option(models.Model):
    class Meta:
        abstract = True

    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self) -> str:
        return self.name


class FrameTypeOption(Option):
    class Meta:
        verbose_name = "Тип платы"
        verbose_name_plural = "Типы плат"

    @classmethod
    def get_default(cls):
        frame_type, _ = cls.objects.get_or_create(name="АМ")
        return frame_type.pk


class BodyOption(Option):
    class Meta:
        verbose_name = "Тип корпуса"
        verbose_name_plural = "Типы корпусов"

    @classmethod
    def get_default(cls):
        body_type, _ = cls.objects.get_or_create(name="Плекс")
        return body_type.pk


class Manufacture(models.Model):
    class Meta:
        verbose_name = "Заявка на производство"
        verbose_name_plural = "Заявки на производство"
        ordering = ["-date_create"]

    status = models.ForeignKey(
        Dictionary,
        verbose_name="Статус",
        help_text="В ожидании, в работе ...",
        related_name="manufactures_status",
        on_delete=models.SET_NULL,
        null=True,
        default=get_default_new_manufacture_status,
    )
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    operator = models.ForeignKey(
        Operator,
        verbose_name="Оператор",
        on_delete=models.PROTECT,
    )
    count = models.IntegerField(verbose_name="Количество", default=0)
    client = models.ForeignKey(
        "Client",
        verbose_name="Клиент",
        on_delete=models.PROTECT,
        related_name="manufactures",
    )
    date_shipment = models.DateField(
        verbose_name="Дата отгрузки", blank=True, null=True
    )
    branding = models.BooleanField(verbose_name="Брендирование", default=False)
    comment = models.TextField(verbose_name="Комментарий", blank=True, null=True)

    ticket = models.ForeignKey(
        Ticket,
        verbose_name="Заявка",
        related_name="manufactures",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    @property
    def progress_str_as_list_nomenclatures(self) -> str:
        """return list with count nomenclatures in work and in status ready"""
        list_progress = [
            self.nomenclatures.filter(status=Nomenclature.Status.IN_PROGRESS).count(),
            (
                self.nomenclatures.filter(status=Nomenclature.Status.READY).count()
                + self.nomenclatures.filter(status=Nomenclature.Status.SHIPPED).count()
            ),
        ]
        return ",".join([str(i) for i in list_progress])

    def get_color_status(self):
        color = {
            "in_progress": "blue",
            "ready": "green",
            "new_manufacture_task": "violet",
            "canceled": "grey",
            "shipped": "green",
        }
        return color.get(self.status.code, "detail")

    def get_absolute_url(self):
        return reverse("manufacture-update", kwargs={"pk": self.pk})


class Client(models.Model):
    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ["-name"]

    name = models.CharField(verbose_name="Имя", max_length=100)
    comment = models.TextField(verbose_name="Комментарий", blank=True, null=True)
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"


class Nomenclature(models.Model):
    class Meta:
        verbose_name = "Номенклатура"
        verbose_name_plural = "Номенклатуры"
        ordering = ["-date_create"]

    class BDType(models.TextChoices):
        OUTER = "OU", "Внешний"
        INNER = "IN", "Внутренний"

    class Color(models.TextChoices):
        WHITE = "WH", "Белый"
        GREY = "GR", "Серый"
        BLACK = "BL", "Черный"

    class Status(models.IntegerChoices):
        NEW = 1, "Новый"
        IN_PROGRESS = 2, "В работе"
        READY = 3, "Готово"
        SHIPPED = 4, "Отгружено"
        CANCELED = 5, "Отменено"

    status = models.IntegerField(
        verbose_name="Статус",
        choices=Status.choices,
        default=Status.NEW,
    )

    frame_type = models.ForeignKey(
        FrameTypeOption,
        verbose_name="Тип",
        on_delete=models.PROTECT,
        default=FrameTypeOption.get_default,
    )

    body = models.ForeignKey(
        BodyOption,
        verbose_name="Корпус",
        on_delete=models.PROTECT,
        default=BodyOption.get_default,
    )

    tx_count = models.IntegerField(verbose_name="Количество TX", default=1)
    rx_count = models.IntegerField(verbose_name="Количество RX", default=1)

    mdg = models.BooleanField(verbose_name="MDG", default=False)
    md = models.BooleanField(verbose_name="MD", default=False)
    wifi = models.BooleanField(verbose_name="Wi-Fi", default=False)

    bp_type = models.CharField(
        verbose_name="Тип БП",
        choices=BDType.choices,
        default=BDType.OUTER,
        max_length=2,
    )
    bp_count = models.IntegerField(verbose_name="Количество БП", default=1)

    amperage_6 = models.BooleanField(
        verbose_name="6 А", default=False, help_text="Amperage for RF"
    )
    amperage_3_2 = models.BooleanField(
        verbose_name="3.2 А", default=False, help_text="Amperage for RF"
    )
    amperage_1 = models.BooleanField(
        verbose_name="1 А", default=False, help_text="Amperage for AM"
    )
    amperage_2 = models.BooleanField(
        verbose_name="2 А", default=False, help_text="Amperage for AM"
    )

    illumination = models.BooleanField(verbose_name="Подсветка", default=True)

    comment = models.TextField(verbose_name="Комментарий", blank=True, null=True)
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)

    manufacture = models.ForeignKey(
        Manufacture,
        verbose_name="Заявка на производство",
        on_delete=models.CASCADE,
        related_name="nomenclatures",
        null=True,
        blank=True,
    )

    is_reserving = models.BooleanField(default=False)

    def __str__(self):
        options = []
        if self.mdg:
            options.append("MGD")
        if self.md:
            options.append("MD")
        if self.wifi:
            options.append("WIFI")
        options = "/".join(options)
        illumination = "💡" if self.illumination else ""
        manufacture = f"(Man: {self.manufacture.pk})" if self.manufacture else ""
        return f"[{self.pk}]{self.frame_type} {self.body} RX:{self.tx_count} TX:{self.rx_count} {options} {self.bp_type} {self.bp_count} {illumination} {manufacture}"

    def get_components(self) -> list:
        """return list components from nomenclature"""
        components = []
        components.extend(self.get_components_from_rx())
        components.extend(self.get_components_from_tx())
        components.extend(self.get_components_from_body())
        components.extend(self.get_components_from_bp())
        if self.mdg:
            components.extend(self.get_components_from_mdg())
        components.extend(self.get_components_from_comment())
        return components

    def get_components_from_rx(self) -> list:
        """return list components from rx"""
        components = [f"Плата {self.frame_type} RX" for _ in range(self.rx_count)]
        return components

    def get_components_from_tx(self) -> list:
        """return list components from tx"""
        components = [f"Плата {self.frame_type} TX" for _ in range(self.tx_count)]
        return components

    def get_components_from_body(self) -> list:
        """return list components from body"""
        components = [
            f"Корпус {self.frame_type} {self.body}"
            for _ in range(self.rx_count + self.tx_count)
        ]
        return components

    def get_components_from_mdg(self) -> list:
        """return list components from mdg"""
        components = []
        components.extend(self.get_components_from_mdg_rx())
        components.extend(self.get_components_from_mdg_tx())
        return components

    def get_components_from_mdg_rx(self) -> list:
        """return list components from mdg rx"""
        components = [f"Плата {self.frame_type} MDG RX" for _ in range(self.rx_count)]
        return components

    def get_components_from_mdg_tx(self) -> list:
        """return list components from mdg tx"""
        components = [f"Плата {self.frame_type} MDG TX" for _ in range(self.tx_count)]
        return components

    def get_components_from_bp(self) -> list:
        """return list components from bp"""
        if self.frame_type == FrameTypeOption.objects.get(name="АМ"):
            return self.get_components_from_bp_am()
        return self.get_components_from_bp_rf()

    def get_components_from_bp_am(self) -> list:
        """return list components from bp am"""
        amperage = "2А" if self.amperage_2 else "1А"
        components = [f"БП АМ {amperage}" for _ in range(self.bp_count)]
        components.extend([f"Плата БП АМ" for _ in range(self.bp_count)])
        return components

    def get_components_from_bp_rf(self) -> list:
        """return list components from bp rf"""
        components = []
        if self.bp_type == "OU":
            amperage = "6А" if self.amperage_6 else "3.2А"
            components = [f"БП РЧ {amperage}" for _ in range(self.bp_count)]
        return components

app/manufactures/forms.py
from django import forms

from ticket.widgets import CalendarInput
from ticsys.widgets import Dropdown
from additionally.models import DictionaryType, Dictionary
from .models import Manufacture, Nomenclature


class ManufactureForm(forms.ModelForm):
    class Meta:
        model = Manufacture
        fields = [
            "status",
            "client",
            "date_shipment",
            "branding",
            "comment",
            "ticket",
        ]
        widgets = {
            "date_shipment": CalendarInput(),
            "comment": forms.Textarea(attrs={"rows": 2, "placeholder": "Комментарий"}),
            "client": Dropdown(attrs={"class": "ui selection dropdown search"}),
            "status": Dropdown(attrs={"class": "ui selection dropdown"}),
            "ticket": Dropdown(attrs={"class": "ui selection dropdown search"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        type_status = DictionaryType.objects.get(code="status_manufactory")
        self.fields["status"].queryset = Dictionary.objects.filter(
            type_dict=type_status
        )


class NomenclatureForm(forms.ModelForm):
    id = forms.IntegerField(
        widget=forms.HiddenInput(), required=False, label="id_nomenclature"
    )

    class Meta:
        model = Nomenclature
        fields = (
            "id",
            "frame_type",
            "body",
            "tx_count",
            "rx_count",
            "mdg",
            "md",
            "wifi",
            "bp_type",
            "bp_count",
            "illumination",
            "comment",
            "status",
            "amperage_6",
            "amperage_3_2",
            "amperage_1",
            "amperage_2",
        )
        widgets = {
            "comment": forms.Textarea(attrs={"rows": 2, "placeholder": "Комментарий"}),
            "frame_type": forms.Select(
                attrs={"class": "ui selection dropdown frame_type"}
            ),
            "body": forms.Select(attrs={"class": "ui selection dropdown"}),
            "bp_type": forms.Select(attrs={"class": "ui selection dropdown"}),
            "status": forms.Select(attrs={"class": "ui selection dropdown"}),
            "amperage_6": forms.CheckboxInput(attrs={"class": "ui checkbox"}),
            "amperage_3_2": forms.CheckboxInput(attrs={"class": "ui checkbox"}),
            "amperage_1": forms.CheckboxInput(attrs={"class": "ui checkbox"}),
            "amperage_2": forms.CheckboxInput(attrs={"class": "ui checkbox"}),
        }


class ManufactureChangeStatusForm(forms.ModelForm):
    status = forms.ModelChoiceField(
        queryset=Dictionary.objects.filter(type_dict__code="status_manufactory"),
    )

    class Meta:
        model = Manufacture
        fields = ("status",)
        widgets = {
            "status": forms.Select(attrs={"class": "ui selection dropdown"}),
        }

app/manufactures/templates/manufactures/client_form.html
{% extends 'ticsys/index.html' %}
{% block content %}
<h1>{% firstof name_page 'Создание клиента' %}</h1>
<div class="ui container">
    <form class="ui form" method="post">
        {{ form.non_field_errors }}
        {% csrf_token %}
        {% for field in form %}
        <div class="field">
            {{ field.errors }}
            {{ field.label_tag }} 
            {{ field }}
        </div>
        {% endfor %}
      <button class="ui button" type="submit">{% firstof name_btn 'Создать' %}</button>
    </form>
  </div>
{% endblock content %}

app/manufactures/templates/manufactures/manufacture_change_status.html
<form class="ui form" method="post" action="{% url 'manufacture-update-status' object.pk %}">
    {{ form.non_field_errors }}
  {% csrf_token %}
  <div class="field">
    <label>{{form.status.label}}</label>
    {{form.status}}
    {{form.status.errors}}
</div>
  <button class="ui button" type="submit">Изменить статус</button>
</form>

app/manufactures/templates/manufactures/manufacture_nomenclatures.html
<div class="ui divided items">
{% for nomenclature in manufacture.nomenclatures.all %}

<div class="item">
    <div class="ui image">

        {% if nomenclature.illumination %}
        <i class="lightbulb yellow icon big"></i>
        {% else %}
        <i class="lightbulb outline icon big"></i>
        {% endif %}
        <br>
        <span class="ui small text grey">#{{nomenclature.pk}}</span>
        <br>
        {% if nomenclature.is_reserving %}
            <button class="ui loading button mini disabled">
                <span class="ui small text red">Резервирование компонентов</span>
            </button>
        {% else %}
            <a href="{% url 'nomenclature-components' nomenclature.pk %}" class="ui label mini">Компоненты</a>
        {% endif %}
        
    </div>
    <div class="content">
       
        <div class="header"> 
            <span class="ui {% if nomenclature.status == 3 %}green {% elif nomenclature.status == 2 %} yellow {% endif %} text">Тип: {{ nomenclature.frame_type }}. Корпус: {{ nomenclature.body }}</span>
            <div class="ui {% if nomenclature.status == 3 %}green {% elif nomenclature.status == 2 %} yellow {% endif %} horizontal label">{{ nomenclature.get_status_display }}</div>
        </div>

        <div class="meta">
            <span class="">TX: {{ nomenclature.tx_count }}</span>
            <span class="">RX: {{ nomenclature.rx_count }}</span>
        </div>
        <div class="description">
            <p>Тип БП: <b>{{ nomenclature.get_bp_type_display }}</b> ({{ nomenclature.bp_count }} шт.) 
                {% if nomenclature.amperage_3_2 %}
                    <i class="bolt yellow icon"></i>3.2А
                {% endif %}
                {% if nomenclature.amperage_6 %}
                    <i class="bolt yellow icon"></i>6А
                {% endif %}
                {% if nomenclature.amperage_1 %}
                    <i class="bolt yellow icon"></i>1А
                {% endif %}
                {% if nomenclature.amperage_2 %}
                    <i class="bolt yellow icon"></i>2А
                {% endif %}
            {% if nomenclature.comment %}
            <p class="componentsComment">Комментарий: {{ nomenclature.comment }}</p>
            {% endif %}
        </div>
        <div class="extra">
            {% if nomenclature.mdg %} <div class="ui label green">MDG</div>{% endif %}
            {% if nomenclature.md %} <div class="ui label green">MD</div>{% endif %}
            {% if nomenclature.wifi %} <div class="ui label green">Wi-Fi</div>{% endif %}
        </div>
    </div>
</div>
{% endfor %}
</div>

app/manufactures/templates/manufactures/manufacture_nomenclatures_print.html
{% extends "ticsys/base.html" %}
{% block common_content%}
    <h1>Информация о заявке № {{manufacture.id}}</h1>
    <div class="ui segment">
        <p>Дата отгрузки: <b>{{manufacture.date_shipment}}</b></p>
        <p>Клиент: <b>{{manufacture.client}}</b></p>
        <p>Брендирование: {% if manufacture.branding%}<b>ДА</b>{% else %}<b>НЕТ</b>{% endif %}
    </div>
    <div class="ui divided items">
        {% for nomenclature in manufacture.nomenclatures.all %}
        <div class="item">
            <div class="ui image">
                {% if nomenclature.illumination %}
                <i class="lightbulb yellow icon big">+</i>
                
                {% else %}
                <i class="lightbulb outline icon big">-</i>
                {% endif %}
                <br>
                <a class="ui  mini label">#{{nomenclature.pk}}</a>
            </div>
            <div class="content">
               
                <div class="header"> <span class="ui {% if nomenclature.status == "RD"  %}green  {% elif  nomenclature.status == "IP"  %} yellow {% endif %} text">Тип: {{ nomenclature.get_frame_type_display}}. Корпус: {{ nomenclature.body}}</span>  <div class="ui basic  horizontal label">{{ nomenclature.get_status_display}}</div></div>
        
                <div class="meta">
                    <span class="">TX: {{nomenclature.tx_count}}</span>
                    <span class="">RX: {{nomenclature.rx_count}}</span>
                    <a class="ui grey circular label">2</a>
                </div>
                <div class="description">
                    <p>Тип БП: <b>{{ nomenclature.get_bp_type_display}}</b> ({{ nomenclature.bp_count}} шт.) 
                        {% if nomenclature.amperage_3_2%}
                            <i class="bolt yellow icon"></i>3.2А
                        {% endif %}
                        {% if nomenclature.amperage_6 %}
                            <i class="bolt yellow icon"></i>6А
                        {% endif %}
                        {% if nomenclature.amperage_1 %}
                            <i class="bolt yellow icon"></i>1А
                        {% endif %}
                        {% if nomenclature.amperage_2 %}
                            <i class="bolt yellow icon"></i>2А
                        {% endif %}
                    {% if nomenclature.comment %}
                    <p>Комментарий: {{ nomenclature.comment}}</p>
                    {% endif %}
                </div>
                <div class="extra">
                    {% if nomenclature.mdg %} <div class="ui label basic">MDG</div>{% endif %}
                    {% if nomenclature.md %} <div class="ui label basic">MD</div>{% endif %}
                    {% if nomenclature.wifi %} <div class="ui label basic">Wi-Fi</div>{% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
        </div>
        <div class="ui segment">
            <p>Комментарий: {{manufacture.comment}}</p>
        </div>
        
{% endblock common_content%}

app/manufactures/templates/manufactures/nomenclature_form.html
<div id="form_nomenclature_{{ form.prefix }}" class="ui raised red segment form-nomenclature">
  {{ form.non_field_errors }}
  {% if form.id.value %}
    <div class="ui red right ribbon icon label label_id">
      <a href="{% url 'nomenclature-components' form.id.value %}">#{{ form.id.value }}</a>
    </div>
  {% endif %}
  <div class="field">
    {{ form.id }}
    <div class="eight fields">
      <div class="field">
        <label>{{ form.frame_type.label }}</label>
        {{ form.frame_type }}
        {{ form.frame_type.error }}
      </div>
      <div class="field">
        <label>{{ form.body.label }}</label>
        {{ form.body }}
        {{ form.body.error }}
      </div>
      <div class="field">
        <label>{{ form.tx_count.label }}</label>
        {{ form.tx_count }}
        {{ form.tx_count.error }}
      </div>
      <div class="field">
        <label>{{ form.rx_count.label }}</label>
        {{ form.rx_count }}
        {{ form.rx_count.error }}
      </div>
      <div class="field">
        <label>{{ form.bp_type.label }}</label>
        {{ form.bp_type }}
        {{ form.bp_type.error }}
      </div>
      <div class="field">
        <label>{{ form.bp_count.label }}</label>
        {{ form.bp_count }}
        {{ form.bp_count.error }}
      </div>
      <div class="field">
        <label>{{ form.status.label }}</label>
        {{ form.status }}
        {{ form.status.error }}
      </div>
      <div class="field">
        <label>{{ form.illumination.label }}</label>
        <div class="ui right aligned toggle checkbox">{{ form.illumination }}</div>
        {{ form.illumination.error }}
      </div>
    </div>
  </div>
  <div class="field">
    <div class="tree fields">
      <div class="field">
        <div class="ui segment">
          <div class="field ui right aligned toggle checkbox">
            <label>{{ form.mdg.label }}</label>
            {{ form.mdg }}
            {{ form.mdg.error }}
          </div>
          <div class="field ui right aligned toggle checkbox">
            <label>{{ form.md.label }}</label>
            {{ form.md }}
            {{ form.md.error }}
          </div>
          <div class="field ui right aligned toggle checkbox">
            <label>{{ form.wifi.label }}</label>
            {{ form.wifi }}
            {{ form.wifi.error }}
          </div>
        </div>
      </div>

      <div class="field" id="amperag-field-{{ form.prefix }}" style="display:none">
        <label>Ампераж БП</label>
        <div class="tree fields">
          <div class="field">
            <div class="ui checkbox">
              {{ form.amperage_6 }}
              <label>{{ form.amperage_6.label }}</label>
              {{ form.amperage_6.error }}
            </div>
          </div>
          <div class="field">
            <div class="ui checkbox">
              {{ form.amperage_3_2 }}
              <label>{{ form.amperage_3_2.label }}</label>
              {{ form.amperage_3_2.error }}
            </div>
          </div>
        </div>
      </div>
      <div class="field" id="amperag-AM-field-{{ form.prefix }}" style="display:none">
        <label>Ампераж БП</label>
        <div class="tree fields">
          <div class="field">
            <div class="ui checkbox">
              {{ form.amperage_1 }}
              <label>{{ form.amperage_1.label }}</label>
              {{ form.amperage_1.error }}
            </div>
          </div>
          <div class="field">
            <div class="ui checkbox">
              {{ form.amperage_2 }}
              <label>{{ form.amperage_2.label }}</label>
              {{ form.amperage_2.error }}
            </div>
          </div>
        </div>
      </div>
      <div class="eight wide field">{{ form.comment }}
        {{ form.comment.error }}</div>
      <div class="field">
        <a class="ui icon basic button mini" id="btn_add_comment_{{ form.prefix }}" onclick="append_comment('{{ form.prefix }}')"><i class="magic icon"></i></a>
      </div>
    </div>
  </div>
  <div class="ui bottom right attached label">
    <a class="ui icon red label" id="btn_remove_nom_{{ form.prefix }}" onclick="remove_nomenclature('{{ form.prefix }}')"><i class="trash icon"></i></a>
  </div>
</div>