app/reports/urls.py
from django.urls import path
from .views import CreateReportView, DownloadReport, ReportListView


urlpatterns = [
    path("create", CreateReportView.as_view(), name="create-report"),
    path("download-report/<int:pk>", DownloadReport.as_view(), name="download-report"),
    path("", ReportListView.as_view(), name="report-list"),
]

app/share/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.ShareCreateView.as_view(), name="create-share"),
    path("delete/<int:pk>", views.DeleteShareView.as_view(), name="delete-share"),
    path("<uuid:pk>", views.DetailShareView.as_view(), name="detail-share"),
    path(
        "comment/<uuid:pk>/<int:ticket_pk>",
        views.ShareCommentCreateView.as_view(),
        name="comment-share",
    ),
]

app/ticsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("users.urls")),
    path("reports/", include("reports.urls")),
    path("share/", include("share.urls")),
    path("manufactures/", include("manufactures.urls")),
    path("storage/", include("storage.urls")),
    path("", include("ticket.urls")),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    if settings.USE_DEBUG_TOOLBAR:
        from debug_toolbar.toolbar import debug_toolbar_urls

        urlpatterns += debug_toolbar_urls()

app/reports/models.py
from collections import namedtuple
from tempfile import NamedTemporaryFile

import openpyxl
from additionally.models import Dictionary
from django.conf import settings
from django.db import models
from django.db.models import Q
from docxtpl import DocxTemplate
from openpyxl.cell.cell import Cell
from openpyxl.styles import Alignment, Color, Font, PatternFill
from openpyxl.styles.borders import Border, Side
from openpyxl.worksheet.worksheet import Worksheet
from ticket.models import Ticket
from users.models import User

ALIGNMENT_DEFAULT = Alignment(horizontal="center", vertical="center", wrapText=True)
alignment_not_wrap = Alignment(horizontal="center", vertical="center", wrapText=True)
alignment_wrap_left = Alignment(horizontal="left", vertical="center", wrapText=True)
font_bold = Font(size=14, bold=True)
FONT_DEFAULT = Font(size=14, bold=False)
color = Color(rgb="3aaacf")
BORDER_DEFAULT = Border(
    left=Side(style="thin"),
    right=Side(style="thin"),
    top=Side(style="thin"),
    bottom=Side(style="thin"),
)

StyleField = namedtuple("StyleField", ["border", "alignment", "font", "fill", "length"])

style_title = StyleField(BORDER_DEFAULT, ALIGNMENT_DEFAULT, font_bold, None, None)
style_title_not_bold = StyleField(None, alignment_not_wrap, FONT_DEFAULT, None, None)

row_style = StyleField(BORDER_DEFAULT, alignment_wrap_left, FONT_DEFAULT, None, None)
row_style_bold = StyleField(BORDER_DEFAULT, alignment_wrap_left, font_bold, None, None)
row_style_center = StyleField(
    BORDER_DEFAULT, ALIGNMENT_DEFAULT, FONT_DEFAULT, None, None
)
row_style_number = StyleField(BORDER_DEFAULT, ALIGNMENT_DEFAULT, FONT_DEFAULT, None, 1)
row_style_comment = StyleField(
    BORDER_DEFAULT, alignment_wrap_left, FONT_DEFAULT, None, 60
)


class Report(models.Model):
    COMMENT_SEP = "\n------------\n"

    class Meta:
        verbose_name = "Отчет"
        verbose_name_plural = "Отчеты"
        ordering = ["-date_create"]

    date_create = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    start_date = models.DateField(verbose_name="Дата начала")
    end_date = models.DateField(verbose_name="Дата окончания")
    creator = models.ForeignKey(
        User, verbose_name="Создатель", related_name="reports", on_delete=models.CASCADE
    )
    file = models.FileField(upload_to="reports/%Y/%m/", verbose_name="Отчет")

    def __str__(self):
        return f"{self.start_date}-{self.end_date} [{self.date_create}]"

    @property
    def file_name(self):
        return self.file.name.split("/")[-1]

    def get_tickets_to_report(self):
        status = Dictionary.get_status_ticket("done")
        warranty = Dictionary.get_type_ticket("warranty")
        tickets = Ticket.objects.filter(
            Q(status=status)
            & ~Q(type_ticket=warranty)
            & (
                Q(completion_date__date__lte=self.end_date)
                | Q(date_update__date__lte=self.end_date)
            )
            & (
                Q(completion_date__date__gte=self.start_date)
                | Q(date_update__date__gte=self.start_date)
            )
        )
        return tickets

    def create_report(self):
        tickets = self.get_tickets_to_report()
        self.create_excel_file(tickets)

    def get_comments(self, ticket: Ticket) -> str | None:
        comments = ticket.get_comments_for_report()
        comments_report_texts = [
            comment.comments_to_str_for_report() for comment in comments if comment.text
        ]
        comments_text = self.COMMENT_SEP.join(comments_report_texts)  # type: ignore
        return comments_text

    def create_excel_file(self, tickets):
        """
        Create excel file with tickets
        """

        wb = openpyxl.Workbook()
        ws: Worksheet = wb.active
        ws.title = "Отчет"
        ws.append(self.header_style(ws))
        for num, ticket in enumerate(tickets):
            comments_text = self.get_comments(ticket)
            start_date = ticket.date_to_work or ticket.date_create
            end_date = ticket.completion_date or ticket.date_update
            start_date = start_date.strftime("%d.%m.%Y")
            end_date = end_date.strftime("%d.%m.%Y")

            values = [
                num + 1,
                ticket.sap_id,
                ticket.shop_id,
                ticket.address,
                start_date,
                end_date,
                comments_text,
            ]
            ws.append(self.row_style(ws, num + 2, values))
        with NamedTemporaryFile() as tmp:
            wb.save(tmp.name)
            self.file.save(f"{self.start_date}-{self.end_date}.xlsx", tmp)

    def header_style(self, ws: Worksheet):
        headers = [
            " ",
            "№ Заявки ДМ",
            "Наименование Объекта",
            "Адрес Объекта (магазина «Детский мир»)",
            "Дата принятия в работу",
            "Дата закрытия заявки",
            "Комментарии",
        ]
        for header in headers:
            c = Cell(ws, column=headers.index(header) + 1, row=1, value=header)
            self.set_style(c, ws, style=style_title)
            # c.length = style_title.length

            yield c

    def row_style(self, ws: Worksheet, row_num, data):
        number_row = 0
        date_start = 4
        date_end = 5
        sap_id = 1
        comment = 6

        for num, value in enumerate(data):
            c = Cell(ws, column=num + 1, row=row_num, value=value)
            if num == number_row:
                self.set_style(c, ws, style=row_style_number)
            if num in (date_start, date_end):
                self.set_style(c, ws, style=row_style_center)
            elif num == sap_id:
                self.set_style(c, ws, style=row_style_bold)
            elif num == comment:
                self.set_style(c, ws, style=row_style_comment)
            else:
                self.set_style(c, ws, style=row_style)
            yield c

    def set_style(self, c, ws: Worksheet, style):
        if style.border:
            c.border = style.border
        if style.alignment:
            c.alignment = style.alignment
        if style.font:
            c.font = style.font
        if style.fill:
            c.fill = style.fill
        if style.length:
            ws.column_dimensions[c.column_letter].width = style.length
        else:
            length = len(str(c.value)) + 6
            length = length if length > 10 else 10
            ws.column_dimensions[c.column_letter].width = length


class Act(models.Model):
    class Meta:
        verbose_name = "Акт выполненных работ"
        verbose_name_plural = "Акты выполненных работ"

    ticket = models.OneToOneField(
        Ticket, verbose_name="Заявка", on_delete=models.CASCADE
    )

    date_create = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    file_doc_act = models.FileField(
        upload_to="secret/acts/%Y/%m/", verbose_name="Акт выполненных работ"
    )

    def create_act(self):
        template_dir = settings.BASE_DIR / "reports/templates/reports/act"
        template = template_dir / "act_DM.docx"
        doc = DocxTemplate(template)
        context = self.get_context()
        doc.render(context)
        with NamedTemporaryFile() as tmp:
            doc.save(tmp.name)
            self.file_doc_act.save(f"{self.ticket.pk}.docx", tmp)

    def __str__(self) -> str:
        return f"Акт {self.ticket}"

    def get_context(self):
        date_start = self.ticket.date_to_work or self.ticket.date_create
        date_str = self.get_str_date(date_start)
        org = " "
        if hasattr(self.ticket, "customer") and self.ticket.customer.profile.company:
            org = self.ticket.customer.profile.company
        context = {"ticket": self.ticket, "date": date_str, "org": org}
        return context

    def get_str_date(self, date):
        month = {
            1: "января",
            2: "февраля",
            3: "марта",
            4: "апреля",
            5: "мая",
            6: "июня",
            7: "июля",
            8: "августа",
            9: "сентября",
            10: "октября",
            11: "ноября",
            12: "декабря",
        }
        date_str = f"«{date.day}» {month[date.month]} {date.year}"
        return date_str

app/reports/forms.py
from django import forms

from ticket.widgets import CalendarInput

from .models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ["start_date", "end_date"]

        widgets = {
            "start_date": CalendarInput(),
            "end_date": CalendarInput(),
        }

app/reports/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views.generic import FormView, ListView, View
from ticket.mixin import AccessOperatorMixin

from .forms import ReportForm
from .models import Report


class CreateReportView(LoginRequiredMixin, AccessOperatorMixin, FormView):
    template_name = "reports/create.html"
    form_class = ReportForm
    success_url = "/reports/"

    def form_valid(self, form):
        report: Report = form.save(commit=False)
        report.creator = self.request.user
        report.create_report()
        return super(CreateReportView, self).form_valid(form)


class ReportListView(LoginRequiredMixin, AccessOperatorMixin, ListView):
    model = Report
    template_name = "reports/list.html"
    ordering = "-date_create"


class DownloadReport(LoginRequiredMixin, AccessOperatorMixin, View):
    def get(self, request, *args, **kwargs):
        report = Report.objects.get(pk=kwargs["pk"])
        response = HttpResponse(report.file, content_type="application/pdf")
        response["Content-Disposition"] = f"attachment; filename={report.file_name}"
        return response

app/reports/templates/reports/create.html
{% extends 'ticsys/index.html' %}
{% block content %}
<h1>{% firstof name_page 'Создание отчета' %}</h1>
<div class="ui container">
    <form class="ui form" method="post">
        {{ form.non_field_errors }}
        {% csrf_token %}
        {% for field in form %}
        <div class="field">
            {{ field.errors }}
            {{ field.label_tag }} 
            {{ field }}
        </div>
        {% endfor %}
      <button class="ui button" type="submit">{% firstof name_btn 'Создать' %}</button>
    </form>
  </div>
{% endblock content %}

{% block script %}
<script>
  $('#date_calendar_start_date').calendar({
    type: 'date',
    endCalendar: $('#date_calendar_end_date'),
    firstDayOfWeek: 1,
    text: {
    days: ['В', 'П', 'В', 'С', 'Ч', 'П', 'С'],
      today: 'Сегодня',
      months: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
      monthsShort: ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"],
    },
    formatter: {
      date: 'DD.MM.YYYY'
    }
  });
  $('#date_calendar_end_date').calendar({
    type: 'date',
    startCalendar: $('#date_calendar_start_date'),
    firstDayOfWeek: 1,
    text: {
    days: ['В', 'П', 'В', 'С', 'Ч', 'П', 'С'],
      today: 'Сегодня',
      months: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
      monthsShort: ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"],
    },
    formatter: {
      date: 'DD.MM.YYYY'
    }
  });
</script>
{% endblock script %}

app/reports/templates/reports/list.html
{% extends 'ticsys/index.html' %}
{% load static %}
{% block header_style %}
<link rel="stylesheet" type="text/css" href="{% static 'DataTables/DataTables-1.13.1/css/dataTables.semanticui.min.css' %}"/> 
<script type="text/javascript" src="{% static 'DataTables/DataTables-1.13.1/js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'DataTables/DataTables-1.13.1/js/dataTables.semanticui.min.js' %}"></script>
{% endblock %}
{% block content %}
<h1>Отчеты</h1>
<a class="ui button" style="margin-bottom: 10px;" href="{% url 'create-report' %}">Создать отчет</a>
<table id="tableCastomers" class="ui table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Дата создания</th>
            <th>Период</th>
            <th>Скачать</th>

        </tr>
    </thead>
    <tbody>
    {% for report in report_list  %}
    <tr>
        <td>{{ report.id }}</td>
        <td>{{ report.date_create|date:"Y-m-d" }}</td>
        <td>{{ report.start_date }}-{{report.end_date}} </td>
        <td><a href="{% url 'download-report' report.id %}" class="ui button basic">Скачать</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

{% block script %}
<script>
var table = $('#tableCastomers').DataTable({
    stateSave: true,
    columnDefs: [
            {
                targets: 1,
                render: DataTable.render.date(),
            },
        ],
    order: [[0, 'desc']],
    language: {
        url: "{% static 'DataTables/ru.json'%}"
    }
      
  });
</script>
{% endblock script %}